/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:574139d8-2676-436e-92e1-b73fba06a9b9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_gwUY0u3K2",
    "aws_user_pools_web_client_id": "32s6oh2mrg12vn7em8no9ebvig",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xtcobkpvazecvnyuuvjcfsop2e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rwpmfryb3rcvzlntxo5gng2ila"
};


export default awsmobile;
